### homework (EDA)
1. country นี้ ใช้กี่มาตรการ
2. มาตรการนี้ ใช้กี่ประเทศ

In [55]:
import pandas as pd
import numpy as np
import psycopg2
import sys, os
import pandas.io.sql as psql
import sqlalchemy  # Package for accessing SQL databases via Python

In [68]:
f = open('db.txt', 'r')
host = f.readline().strip()
dbname = f.readline().strip()
user = f.readline().strip()
password = f.readline().strip()
schema = f.readline().strip()
database = f.readline().strip()
f.close()

In [ ]:
# Connect to database (Note: The package psychopg2 is required for Postgres to work with SQLAlchemy)

engine = sqlalchemy.create_engine("postgresql://{}:{}@{}/{}".format(user, password, host, database))
con = engine.connect()

# Verify that there are no existing tables
print(engine.table_names())

In [58]:
table = "measures"
schema = "public" #always public

# Command
sql_command = "SELECT * FROM {}.{};".format(str(schema), str(table))
print (sql_command)
measures_df = pd.read_sql(sql_command,
                     con=engine,
                    index_col="index")

print(measures_df.shape)

SELECT * FROM public.measures;
(3928, 8)

In [59]:
measures_df

,COUNTRY,MEASURE,LOG_TYPE,ADMIN_LEVEL_NAME,REGION,CATEGORY,DATE_IMPLEMENTED,ENTRY_DATE
index,,,,,,,,
0,Australia,awareness campaigns,Introduction / extension of measures,-,Pacific,Public health measures,2020-03-17,2020-03-21 00:00:00
1,Australia,awareness campaigns,Introduction / extension of measures,NSW,Pacific,Public health measures,2020-04-08,2020-04-09 00:00:00
2,Australia,awareness campaigns,Introduction / extension of measures,NT,Pacific,Public health measures,2020-03-26,2020-03-27 00:00:00
3,Australia,awareness campaigns,Introduction / extension of measures,WA,Pacific,Public health measures,2020-04-27,2020-04-27 00:00:00
4,Australia,border closure,Introduction / extension of measures,-,Pacific,Movement restrictions,2020-03-20,2020-03-21 00:00:00
...,...,...,...,...,...,...,...,...
3923,Zimbabwe,other public health measures enforced,Phase-out measure,-,Africa,Public health measures,2020-04-03,2020-04-07 00:00:00
3924,Zimbabwe,requirement to wear protective gear in public,Introduction / extension of measures,-,Africa,Public health measures,2020-05-04,2020-05-25 00:00:00
3925,Zimbabwe,schools closure,Introduction / extension of measures,-,Africa,Social distancing,2020-03-24,2020-03-24 00:00:00
3926,Zimbabwe,state of emergency declared,Introduction / extension of measures,-,Africa,Governance and socio-economic measures,2020-03-17,2020-04-10 00:00:00
3927,Zimbabwe,testing policy,Introduction / extension of measures,-,Africa,Public health measures,2020-04-15,2020-04-15 00:00:00

In [60]:
measures_df.MEASURE.unique()

array(['awareness campaigns', 'border closure',
       'changes in prison-related policies',
       'closure of businesses and public services',
       'domestic travel restrictions', 'economic measures',
       'emergency administrative structures activated or established',
       'general recommendations', 'international flights suspension',
       'isolation and quarantine policies', 'limit public gatherings',
       'lockdown', 'military deployment',
       'other public health measures enforced',
       'psychological assistance and medical social work',
       'schools closure', 'state of emergency declared',
       'strengthening the public health system',
       'surveillance and monitoring', 'testing policy',
       'visa restrictions',
       'health screenings in airports and border crossings',
       'requirement to wear protective gear in public',
       'additional health/documents requirements upon arrival',
       'checkpoints within the country', 'mass population testing',
       'amendments to funeral and burial regulations', 'border checks',
       'limit product imports/exports',
       'lockdown of refugee/idp camps or other minorities', 'curfews',
       'humanitarian exemptions', 'complete border closure'], dtype=object)

In [61]:
eda1_df['COUNTRY'].unique()

array(['Afghanistan', 'Australia', 'Brazil', 'China', 'Germany', 'Iraq',
       'Italy', 'Russia', 'Thailand', 'US', 'United Kingdom', 'Vietnam',
       'Burkina Faso', 'Myanmar', 'Bahamas', 'Eritrea', 'Kyrgyzstan',
       'Dominican Republic', 'Slovenia', 'Palau', 'Iceland', 'Tunisia',
       'Albania', 'Uganda', 'Serbia', 'Luxembourg', 'Cabo Verde',
       'Venezuela', 'Botswana', 'Ecuador', 'Estonia', 'Korea, North'],
      dtype=object)

In [62]:
show_country_list = ['China', 'Thailand', 'US', 'United Kingdom', 'Brazil', 'Australia', 'Taiwan', 'Korea, Southt', 'Iraq', 'Afghanistan', 'Vietnam', 'Italy', 'Russia', 'Germany']

In [63]:
eda1_df = measures_df.groupby(['COUNTRY'])['MEASURE'].nunique().reset_index()
eda1_tail_df = eda1_df[~eda1_df['COUNTRY'].isin(show_country_list)]
eda1_df = eda1_df[eda1_df['COUNTRY'].isin(show_country_list)]
eda1_df

            COUNTRY  MEASURE
0       Afghanistan       17
7         Australia       21
22           Brazil       16
34            China       24
63          Germany       20
78             Iraq       15
81            Italy       27
141          Russia       16
169        Thailand       22
178              US       19
182  United Kingdom       13
187         Vietnam       20

In [64]:
eda1_df = pd.concat([eda1_df, eda1_tail_df.sample(16)])
eda1_df

                   COUNTRY  MEASURE
0              Afghanistan       17
7                Australia       21
22                  Brazil       16
34                   China       24
63                 Germany       20
78                    Iraq       15
81                   Italy       27
141                 Russia       16
169               Thailand       22
178                     US       19
182         United Kingdom       13
187                Vietnam       20
152             Seychelles       15
162                  Sudan       20
41                    Cuba       17
123              Nicaragua       11
98           Liechtenstein       14
130                  Palau       13
114             Montenegro       15
14                 Belarus       15
16                  Belize       20
26                 Burundi        7
148  Sao Tome and Principe       13
127                 Norway       19
37     Congo (Brazzaville)       15
121            Netherlands       10
50                   Egypt       15
19                 Bolivia       17

In [65]:
eda2_df = measures_df.groupby(['MEASURE'])['COUNTRY'].nunique()
eda2_df

MEASURE
additional health/documents requirements upon arrival            44
amendments to funeral and burial regulations                     33
awareness campaigns                                             128
border checks                                                    45
border closure                                                  158
changes in prison-related policies                               61
checkpoints within the country                                   25
closure of businesses and public services                       151
complete border closure                                           2
curfews                                                          83
domestic travel restrictions                                    134
economic measures                                               164
emergency administrative structures activated or established    138
general recommendations                                         119
health screenings in airports and border crossings              130
humanitarian exemptions                                           5
international flights suspension                                148
isolation and quarantine policies                               166
limit product imports/exports                                    34
limit public gatherings                                         172
lockdown                                                        131
lockdown of refugee/idp camps or other minorities                10
mass population testing                                          22
military deployment                                              45
other public health measures enforced                           123
psychological assistance and medical social work                 46
requirement to wear protective gear in public                   101
schools closure                                                 165
state of emergency declared                                     106
strengthening the public health system                          161
surveillance and monitoring                                     107
testing policy                                                   88
visa restrictions                                               114
Name: COUNTRY, dtype: int64

In [66]:
eda1_df.to_csv('eda/total_number_of_measure_country_use.csv')

In [67]:
eda2_df.to_csv('eda/total_number_of_country_each_measure_used.csv')

EDA-1
- 20-25 countries
- show high & low for comparison

EDA-2